services:
  web:
    restart: always
    build: ./webserver
    container_name: "web_qachatbot"
    tty: true
    working_dir: "/usr/src/app"
    volumes:
      - ./webserver/app:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
      - 24678:24678
  api:
    restart: always
    build:
      target: builder
      context: ./apserver
    container_name: "api_qachatbot"
    command: ["python","app/main.py"]
    volumes:
      - ./apserver:/opt
    tty: true
    ports:
      - 8000:8000
  loadbalancer:
    image: nginx:1.24-bullseye
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./loadbalancer:/etc/nginx/conf.d:ro

