variable "sg_ecs_id" {}
variable "subnet_private_subnet_1a_id" {}
variable "subnet_public_subnet_1a_id" {}
variable "aws_iam_role" {}
variable "app_name" {}
variable "api_repository_url" {}
variable "lb_target_group_api_arn" {}
variable "api_port" {}
variable "http_arn" {}
